# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Qingping co2 addon
version: "0.0.4"
slug: qingping_co2
description: Qingping co2 add-on
url: "https://github.com/bob-tm/ha-qingping-parser-addon/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
options:
  MQTT_SERVER: ""
  MQTT_PORT: "1883"
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  SENSOR_MAC: ""
  SENSOR_TOPIC: "qingping/SENSOR_MAC/up"
  ADVERTISE_HOME_ASSISTANT: "true"
schema:
  MQTT_SERVER: str
  MQTT_PORT: str
  MQTT_USER: str
  MQTT_PASSWORD: str
  SENSOR_MAC: str
  SENSOR_TOPIC: str
  ADVERTISE_HOME_ASSISTANT: bool
